#!/usr/bin/env python3
"""Generate live workspace indexes without inspecting archived material by default."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

EXCLUDED_PARTS = {"90_archive", "deprecated", ".git", "__pycache__"}
GENERATED_NAMES = {
    "LIVE_FILE_MAP.md",
    "RULE_OWNERSHIP_MAP.md",
    "ASSET_LOCATOR.md",
    "CURRENT_MAINTENANCE_STATUS.md",
    "LEARNING_REVIEW.md",
    "SESSION_BRIEFING_STATUS.md",
    "WORKFLOW_TRACE_BASELINE.json",
}
CANONICAL_OWNERS = (
    ("Session orientation and startup order", "00_START_HERE.md", "Short summaries may link here; do not repeat its full sequence."),
    ("Workspace navigation", "02_INDEX.md", "Curated top-level map only; generated detail belongs in LIVE_FILE_MAP.md."),
    ("Conflict precedence and change governance", "03_GOVERNANCE.md", "Agent files carry an intentional operational summary."),
    ("Business constraints", "04_BUSINESS_RULES.md", "Workflow docs may point here but must not redefine guardrails."),
    ("Product and listing workflow", "06_PRODUCT_DECISION_WORKFLOW.md and 07_LISTING_AND_CONTENT_WORKFLOW.md", "Operational records remain role-specific."),
    ("Automation boundaries", "08_AUTOMATION_ROADMAP.md", "Script runbooks define commands, not policy."),
    ("Schemas and record fields", "09_DATA_MODEL.md", "Templates intentionally restate required fields."),
    ("Prompt navigation", "10_PROMPTS_INDEX.md", "Standalone prompts intentionally carry complete external context."),
    ("Weekly cadence", "11_WEEKLY_OPERATIONS.md", "Weekly scripts are a concise operational aid."),
    ("Decision history", "12_DECISION_LOG.md", "Historical rationale, not a replacement for current policy."),
    ("Brand identity and reusable assets", "00_brand/", "Operational files point here instead of owning competing brand rules."),
    ("Facebook Marketplace rollout", "40_listings/facebook_marketplace_catalog_rollout_2026-06-03.md", "Prompt packs and listing records remain implementation evidence."),
    ("Facebook Page brand-post rules", "50_content/facebook_brand_post_rules.md", "Content records hold instance-level choices."),
    ("External-prompt completeness", "80_templates/standalone_external_prompt_checklist.md", "External prompts intentionally inline the relevant rules."),
    ("Maintenance operation", "60_automation/workspace_maintenance/", "Generated indexes and runbooks live here."),
)


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def is_live(path: Path, root: Path) -> bool:
    return not bool(set(path.relative_to(root).parts) & EXCLUDED_PARTS)


def live_files(root: Path) -> list[Path]:
    return [
        path
        for path in sorted(root.rglob("*"))
        if path.is_file()
        and is_live(path, root)
        and path.name not in GENERATED_NAMES
    ]


def render_live_file_map(root: Path) -> str:
    grouped: dict[str, list[str]] = defaultdict(list)
    for path in live_files(root):
        suffix = path.suffix.lower()
        if suffix in {".md", ".py", ".ps1", ".json", ".csv", ".txt"}:
            relative = rel(path, root)
            parent = str(Path(relative).parent).replace("\\", "/")
            grouped[parent if parent != "." else "Repository root"].append(relative)

    lines = [
        "# Live File Map",
        "",
        "Generated by refresh_live_indexes.py. It lists active text and workflow files only; 90_archive and deprecated paths are intentionally excluded.",
        "",
        "## Use This Map",
        "",
        "- Start at 00_START_HERE.md for operating context.",
        "- Use 02_INDEX.md for the curated human map.",
        "- Use this file when a focused search needs a precise live path.",
    ]
    for parent, paths in sorted(grouped.items()):
        lines.extend(["", f"## {parent}", ""])
        lines.extend(f"- {path}" for path in paths)
    lines.append("")
    return "\n".join(lines)


def render_rule_ownership_map() -> str:
    lines = [
        "# Rule Ownership Map",
        "",
        "Generated by refresh_live_indexes.py. This map prevents the same active rule from being maintained in competing places.",
        "",
        "| Topic | Canonical owner | Intentional copies or boundary |",
        "|---|---|---|",
    ]
    for topic, owner, boundary in CANONICAL_OWNERS:
        lines.append(f"| {topic} | {owner} | {boundary} |")
    lines.extend(
        [
            "",
            "## Classification Rule",
            "",
            "- Canonical owner: update the owner first, then repair pointers.",
            "- Intentional standalone copy: retain complete context that an external target or separate agent tool cannot read from the repository.",
            "- Short pointer or summary: keep it brief and link to the owner.",
            "- Stale or conflicting duplicate: remove, replace with a pointer, or archive when its successor is known.",
            "- Needs user decision: escalate factual, policy, published-record, source-evidence, or ownership uncertainty.",
            "",
        ]
    )
    return "\n".join(lines)


def render_asset_locator(root: Path) -> str:
    brand = root / "00_brand"
    brand_files = [
        rel(path, root)
        for path in sorted(brand.rglob("*"))
        if path.is_file() and path.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp", ".md"}
    ]
    snapshot_root = root / "20_research" / "competitor_snapshots"
    snapshots: list[tuple[str, int]] = []
    if snapshot_root.exists():
        for folder in sorted(path for path in snapshot_root.iterdir() if path.is_dir()):
            media_count = sum(
                1
                for path in folder.rglob("*")
                if path.is_file() and path.suffix.lower() in {".png", ".jpg", ".jpeg", ".heic", ".webp"}
            )
            snapshots.append((rel(folder, root), media_count))

    lines = [
        "# Asset Locator",
        "",
        "Generated by refresh_live_indexes.py. This is a locator, not permission to use any asset in customer-facing media.",
        "",
        "## Reusable Approved Brand Assets",
        "",
        "Use 00_brand/ as the active source of truth. Product, listing, and content records still decide whether an asset is approved for a specific use.",
        "",
    ]
    lines.extend(f"- {path}" for path in brand_files)
    lines.extend(
        [
            "",
            "## External Created Product References",
            "",
            "- Location and filenames: 00_brand/references/PRODUCT_REF_IMAGES_MANIFEST.md",
            "- These remain external created-reference files until an operational record selects them or they are approved as reusable brand assets.",
            "",
            "## Research and Third-Party Snapshots",
            "",
            "- Location: 20_research/competitor_snapshots/",
            "- These are research/source material only and must not be treated as active listing or publishable-content media.",
            "",
        ]
    )
    lines.extend(f"- {folder}: {count} image files" for folder, count in snapshots)
    lines.extend(
        [
            "",
            "## Catalog Provenance",
            "",
            "- Historical catalog source package: 20_research/catalog_exports/2026-06-03/",
            "- It supports provenance only; 00_brand/ owns current reusable identity guidance and approved reusable assets.",
            "",
        ]
    )
    return "\n".join(lines)


def expected_outputs(root: Path) -> dict[Path, str]:
    base = root / "60_automation" / "workspace_maintenance"
    return {
        base / "LIVE_FILE_MAP.md": render_live_file_map(root),
        base / "RULE_OWNERSHIP_MAP.md": render_rule_ownership_map(),
        base / "ASSET_LOCATOR.md": render_asset_locator(root),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="Write generated indexes.")
    action.add_argument("--check", action="store_true", help="Fail if generated indexes are stale.")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    outputs = expected_outputs(root)
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]

    if args.write:
        for path, content in outputs.items():
            path.write_text(content, encoding="utf-8")
            print(f"Wrote {rel(path, root)}")
        return 0

    if stale:
        for path in stale:
            print(f"Stale: {rel(path, root)}")
        return 1
    print("Generated indexes are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
